### ISSUE TITLE
Error during updating: object ‘ergm.Cprepare’ is not exported by 'namespace:ergm'

### ISSUE THREAD

**Issue by smy310** [statnet/tergm#56]
I updated R, Rtools and Rstudio all to the newest version. but I cannot load tergm anymore. 

I tried also to delete the package and install again, but the problem still exists.

It shows always 
Error: package or namespace load failed for ‘btergm’:
object ‘ergm.Cprepare’ is not exported by 'namespace:ergm'

Has someone the same problem and can developer help in this case? Thanks in advance!

**Comment by krivit** [comment]
Thank you for the report! There has been an API change, and this problem should fix itself once the new `tergm` is on CRAN.

**Comment by martinamorris** [comment]
@smy310 we are releasing a major update to the `statnet` packages this month.  We have to release them in order of dependency -- so `ergm` is released before `tergm` -- and CRAN requires that each released package pass all of its tests before the next dependent package can be released, so we are waiting for `ergm` to complete these tests.  The new release of `tergm` will probably be submitted this weekend.

in the meantime, if you need to use the packages, you can roll back to a previous version of `network` and `ergm` by installing these from CRAN (see [here for instructions](https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages))

**Comment by smy310** [comment]
Dear Martina,

Thanks for your suggestion. I tried to load previous version but I have still the same problem. Are you sure that I only need set old version of network and ergm? Maybe other packages also?

Many thanks!


BR,
Sry


2021年6月19日 上午1:54，Martina Morris ***@***.******@***.***>> 写道：



@smy310<https://github.com/smy310> we are releasing a major update to the statnet packages this month. We have to release them in order of dependency -- so ergm is released before tergm -- and CRAN requires that each released package pass all of its tests before the next dependent package can be released, so we are waiting for ergm to complete these tests. The new release of tergm will probably be submitted this weekend.

in the meantime, if you need to use the packages, you can roll back to a previous version of network and ergm by installing these from CRAN (see here for instructions<https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages>)

**Comment by martinamorris** [comment]
You can try also installing the previous version of `statnet.common`.

We released `tergm` to CRAN last night.  That's the last of the updates.  It may take a few days for this to make it through CRAN's testing before it is available.
